name: wakatime-scheduler

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch: 
jobs:
  update-readme:
    name: wakatime-update
    runs-on: ubuntu-latest
    steps:
      -  uses: anmol098/waka-readme-stats@master
         with:
           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_TOKEN }}
           GH_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
           LOCALE: ko
           COMMIT_BY_ME: "True"
           COMMIT_MESSAGE: "wakatime 정보 Readme.md 업데이트"
           SHOW_UPDATED_DATE: "True"
           SHOW_OS: "False"
           SHOW_PROJECTS: "False"
           SHOW_TIMEZONE: "False"
           SHOW_EDITORS: "True"
           SHOW_LOC_CHART: "False"
                     
